### ISSUE TITLE
Latest master breaks `px`

### ISSUE THREAD

**Issue by danwdart** [kowainik/stan#478]
Unsure if expected, but:

```
[ 8 of 43] Compiling Stan.Ghc.Compat

src/Stan/Ghc/Compat.hs:49:1: error:
    Could not find module ‘Avail’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
49 | import Avail (AvailInfo (..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Stan/Ghc/Compat.hs:50:1: error:
    Could not find module ‘BasicTypes’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
50 | import BasicTypes (PromotionFlag (..), TupleSort (..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Stan/Ghc/Compat.hs:51:1: error:
    Could not find module ‘FastString’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
51 | import FastString (FastString)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Stan/Ghc/Compat.hs:52:1: error:
    Could not find module ‘FieldLabel’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
52 | import FieldLabel (FieldLbl (..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Stan/Ghc/Compat.hs:53:1: error:
    Could not find module ‘IfaceType’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
53 | import IfaceType (IfaceTyCon (..), IfaceTyConInfo (..), IfaceTyConSort (..), IfaceTyLit (..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Stan/Ghc/Compat.hs:54:1: error:
    Could not find module ‘Module’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
54 | import Module (Module, ModuleName, moduleName, moduleNameString, moduleStableString, moduleUnitId)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Stan/Ghc/Compat.hs:55:1: error:
    Could not find module ‘Name’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
55 | import Name (Name, isExternalName, nameModule, nameOccName, nameStableString)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Stan/Ghc/Compat.hs:56:1: error:
    Could not find module ‘OccName’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
56 | import OccName (isSymOcc, occNameString)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Stan/Ghc/Compat.hs:57:1: error:
    Could not find module ‘SrcLoc’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
57 | import SrcLoc (RealSrcSpan, srcSpanEndCol, srcSpanEndLine, srcSpanFile, srcSpanStartCol,
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Stan/Ghc/Compat.hs:59:1: error:
    Could not find module ‘Var’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
59 | import Var (ArgFlag (..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^
[10 of 43] Compiling Stan.Hie.Compat

src/Stan/Hie/Compat.hs:36:1: error:
    Could not find module ‘HieBin’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
36 | import HieBin (HieFileResult (hie_file_result), readHieFile)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Stan/Hie/Compat.hs:37:1: error:
    Could not find module ‘HieTypes’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
37 | import HieTypes (ContextInfo (..), DeclType (..), HieAST (..), HieASTs (..), HieArgs (..),
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Stan/Hie/Compat.hs:40:1: error:
    Could not find module ‘NameCache’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
40 | import NameCache (NameCache, initNameCache)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Stan/Hie/Compat.hs:41:1: error:
    Could not find module ‘UniqSupply’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
41 | import UniqSupply (mkSplitUniqSupply)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[12 of 43] Compiling Stan.Info
[15 of 43] Compiling Stan.Pattern.Edsl
[21 of 43] Compiling Stan.Report.Css

src/Stan/Report/Css.hs:44:19: error:
    • Couldn't match expected type ‘Size LengthUnit’
                  with actual type ‘Stroke’
    • In the first argument of ‘borderTop’, namely ‘solid’
      In a stmt of a 'do' block: borderTop solid (px 15) darkGrey
      In the second argument of ‘(?)’, namely
        ‘do display block
            textAlign center
            width (100 %)
            maxWidth (100 %)
            ....’
   |
44 |         borderTop solid (px 15) darkGrey
   |                   ^^^^^

src/Stan/Report/Css.hs:44:26: error:
    • Couldn't match expected type ‘Stroke’
                  with actual type ‘Size LengthUnit’
    • In the second argument of ‘borderTop’, namely ‘(px 15)’
      In a stmt of a 'do' block: borderTop solid (px 15) darkGrey
      In the second argument of ‘(?)’, namely
        ‘do display block
            textAlign center
            width (100 %)
            maxWidth (100 %)
            ....’
   |
44 |         borderTop solid (px 15) darkGrey
   |                          ^^^^^

src/Stan/Report/Css.hs:76:16: error:
    • Couldn't match expected type ‘Size LengthUnit’
                  with actual type ‘Stroke’
    • In the first argument of ‘border’, namely ‘solid’
      In the second argument of ‘(?)’, namely
        ‘border solid (px 1) lightGrey’
      In a stmt of a 'do' block:
        (".observation"
           <> "#configurations" <> "#stan-info" <> "#severity")
          ** (tr <> td <> th)
          ? border solid (px 1) lightGrey
   |
76 |         border solid (px 1) lightGrey
   |                ^^^^^

src/Stan/Report/Css.hs:76:23: error:
    • Couldn't match expected type ‘Stroke’
                  with actual type ‘Size LengthUnit’
    • In the second argument of ‘border’, namely ‘(px 1)’
      In the second argument of ‘(?)’, namely
        ‘border solid (px 1) lightGrey’
      In a stmt of a 'do' block:
        (".observation"
           <> "#configurations" <> "#stan-info" <> "#severity")
          ** (tr <> td <> th)
          ? border solid (px 1) lightGrey
   |
76 |         border solid (px 1) lightGrey
   |                       ^^^^

src/Stan/Report/Css.hs:87:20: error:
    • Couldn't match expected type ‘Size LengthUnit’
                  with actual type ‘Stroke’
    • In the first argument of ‘borderLeft’, namely ‘solid’
      In a stmt of a 'do' block: borderLeft solid (px 4) darkGrey
      In the second argument of ‘(?)’, namely
        ‘do paddingLeft (2 %)
            borderLeft solid (px 4) darkGrey
            boxShadow $ one $ bsColor lightGrey $ shadow (px (- 4)) 0’
   |
87 |         borderLeft solid (px 4) darkGrey
   |                    ^^^^^

src/Stan/Report/Css.hs:87:27: error:
    • Couldn't match expected type ‘Stroke’
                  with actual type ‘Size LengthUnit’
    • In the second argument of ‘borderLeft’, namely ‘(px 4)’
      In a stmt of a 'do' block: borderLeft solid (px 4) darkGrey
      In the second argument of ‘(?)’, namely
        ‘do paddingLeft (2 %)
            borderLeft solid (px 4) darkGrey
            boxShadow $ one $ bsColor lightGrey $ shadow (px (- 4)) 0’
   |
87 |         borderLeft solid (px 4) darkGrey
   |                           ^^^^

src/Stan/Report/Css.hs:130:22: error:
    • Couldn't match expected type ‘Size LengthUnit’
                  with actual type ‘Stroke’
    • In the first argument of ‘borderBottom’, namely ‘solid’
      In a stmt of a 'do' block: borderBottom solid (px 13) transparent
      In the second argument of ‘(?)’, namely
        ‘do backgroundColor c
            borderBottom solid (px 13) transparent
            borderLeft solid (px 10) pink
            borderTop solid (px 13) transparent
            ....’
    |
130 |         borderBottom solid (px 13) transparent
    |                      ^^^^^

src/Stan/Report/Css.hs:130:29: error:
    • Couldn't match expected type ‘Stroke’
                  with actual type ‘Size LengthUnit’
    • In the second argument of ‘borderBottom’, namely ‘(px 13)’
      In a stmt of a 'do' block: borderBottom solid (px 13) transparent
      In the second argument of ‘(?)’, namely
        ‘do backgroundColor c
            borderBottom solid (px 13) transparent
            borderLeft solid (px 10) pink
            borderTop solid (px 13) transparent
            ....’
    |
130 |         borderBottom solid (px 13) transparent
    |                             ^^^^^

src/Stan/Report/Css.hs:131:22: error:
    • Couldn't match expected type ‘Size LengthUnit’
                  with actual type ‘Stroke’
    • In the first argument of ‘borderLeft’, namely ‘solid’
      In a stmt of a 'do' block: borderLeft solid (px 10) pink
      In the second argument of ‘(?)’, namely
        ‘do backgroundColor c
            borderBottom solid (px 13) transparent
            borderLeft solid (px 10) pink
            borderTop solid (px 13) transparent
            ....’
    |
131 |         borderLeft   solid (px 10) pink
    |                      ^^^^^

src/Stan/Report/Css.hs:131:29: error:
    • Couldn't match expected type ‘Stroke’
                  with actual type ‘Size LengthUnit’
    • In the second argument of ‘borderLeft’, namely ‘(px 10)’
      In a stmt of a 'do' block: borderLeft solid (px 10) pink
      In the second argument of ‘(?)’, namely
        ‘do backgroundColor c
            borderBottom solid (px 13) transparent
            borderLeft solid (px 10) pink
            borderTop solid (px 13) transparent
            ....’
    |
131 |         borderLeft   solid (px 10) pink
    |                             ^^^^^

src/Stan/Report/Css.hs:132:22: error:
    • Couldn't match expected type ‘Size LengthUnit’
                  with actual type ‘Stroke’
    • In the first argument of ‘borderTop’, namely ‘solid’
      In a stmt of a 'do' block: borderTop solid (px 13) transparent
      In the second argument of ‘(?)’, namely
        ‘do backgroundColor c
            borderBottom solid (px 13) transparent
            borderLeft solid (px 10) pink
            borderTop solid (px 13) transparent
            ....’
    |
132 |         borderTop    solid (px 13) transparent
    |                      ^^^^^

src/Stan/Report/Css.hs:132:29: error:
    • Couldn't match expected type ‘Stroke’
                  with actual type ‘Size LengthUnit’
    • In the second argument of ‘borderTop’, namely ‘(px 13)’
      In a stmt of a 'do' block: borderTop solid (px 13) transparent
      In the second argument of ‘(?)’, namely
        ‘do backgroundColor c
            borderBottom solid (px 13) transparent
            borderLeft solid (px 10) pink
            borderTop solid (px 13) transparent
            ....’
    |
132 |         borderTop    solid (px 13) transparent
    |                             ^^^^^

src/Stan/Report/Css.hs:142:16: error:
    • Couldn't match expected type ‘Size LengthUnit’
                  with actual type ‘Stroke’
    • In the first argument of ‘border’, namely ‘solid’
      In a stmt of a 'do' block: border solid (px 1) darkGrey
      In the second argument of ‘(?)’, namely
        ‘do display inlineBlock
            padding (px 1) 0 0 0
            border solid (px 1) darkGrey
            borderRadius (px 4) (px 4) (px 4) (px 4)
            ....’
    |
142 |         border solid (px 1) darkGrey
    |                ^^^^^

src/Stan/Report/Css.hs:142:23: error:
    • Couldn't match expected type ‘Stroke’
                  with actual type ‘Size LengthUnit’
    • In the second argument of ‘border’, namely ‘(px 1)’
      In a stmt of a 'do' block: border solid (px 1) darkGrey
      In the second argument of ‘(?)’, namely
        ‘do display inlineBlock
            padding (px 1) 0 0 0
            border solid (px 1) darkGrey
            borderRadius (px 4) (px 4) (px 4) (px 4)
            ....’
    |
142 |         border solid (px 1) darkGrey
    |                       ^^^^

src/Stan/Report/Css.hs:167:21: error:
    • Couldn't match expected type ‘Size LengthUnit’
                  with actual type ‘Stroke’
    • In the first argument of ‘borderRight’, namely ‘solid’
      In a stmt of a 'do' block: borderRight solid (px 1) darkGrey
      In the expression:
        do padding2 (px 0) (px 15)
           height (100 %)
           backgroundColor c
           backgroundClip $ boxClip paddingBox
           ....
    |
167 |         borderRight solid (px 1) darkGrey
    |                     ^^^^^

src/Stan/Report/Css.hs:167:28: error:
    • Couldn't match expected type ‘Stroke’
                  with actual type ‘Size LengthUnit’
    • In the second argument of ‘borderRight’, namely ‘(px 1)’
      In a stmt of a 'do' block: borderRight solid (px 1) darkGrey
      In the expression:
        do padding2 (px 0) (px 15)
           height (100 %)
           backgroundColor c
           backgroundClip $ boxClip paddingBox
           ....
    |
167 |         borderRight solid (px 1) darkGrey
    |                            ^^^^
[22 of 43] Compiling Stan.Report.Settings
[23 of 43] Compiling Stan.Severity
```

Seems to want to compile with 9.4.2

Thanks

**Comment by danwdart** [comment]
I'll have to update my derivations to jailbreak the version of clay used, not the newest, until it does.
Until then I'll close this one and open more for updated versions of dependencies.
